### ISSUE TITLE
[REQUEST] Can you modify windows icon so that looks like the windows 11 icon (squared)

### ISSUE THREAD

**Issue by Human79** [82ghost82/BigSurFlat#1]
[REQUEST] Can you modify windows icon so that looks like the windows 11 icon (squared)

**Comment by 82ghost82** [comment]
Added Windows11.icns:
https://github.com/82ghost82/BigSurFlat/commit/ebc10be622259c11db6a8ac8d20d46d0acb3bbc2

![alt text](https://i.ibb.co/p044wVY/2x.png)

**Comment by Human79** [comment]
Thank you! How about a Windows 10 style one?

**Comment by 82ghost82** [comment]
Added:
https://github.com/82ghost82/BigSurFlat/commit/52f429db0208d2535244c40cf94508e097ec229e

![alt text](https://i.ibb.co/YL2swdg/preview.png)

**Comment by Human79** [comment]
Thank you so much!
